Process approved submissions function
DEFRA/epr-prn-obligationcalculations-function pull request #11
Opened 2024-10-28 11:47 UTC by jayakrishnanappusamy

Updated StoreApprovedSubmissionsFunction (TimerTrigger) to read last run date from queue
Added second function ProcessApprovedSubmissionsFunction (ServiceBusTrigger)

2024-10-28 13:06 UTC, harishpaladugu13 submitted a review, later dismissed

2024-10-29 14:17 UTC, saywasingh-eviden commented on src/EPR.PRN.ObligationCalculation.Application/Services/ServiceBusProvider.cs
> +                if (submissions.Count != 0)
Can this check not be reversed:

if (submissions.Count == 0 )
 Continue;

It would make the flow a little easier to read.

2024-10-29 14:26 UTC, saywasingh-eviden requested changes
See added comment, apart from that, everything else looks good

2024-10-29 14:43 UTC, saywasingh-eviden approved these changes

2024-10-29 14:46 UTC, merged